### ISSUE TITLE
you sussy baka amogus imposter

### ISSUE THREAD

**Issue by anonymousomeone** [Eishaaya/Tetris-2#3]
me when the sussy amogus imposter baka no leave instructs for how to constipation complication compilation ???????

**Comment by anonymousomeone** [comment]
😡😡😡😡😡😡😡me when the amogus baka imposter sussy ghosting me 😡😡😡💀💀💀

**Comment by anonymousomeone** [comment]
https://tenor.com/view/blocked-block-you-blocked-blocking-gif-14145534

**Comment by DkeRee** [comment]
gGgGGgGgggGgggiwiuvGoGOGOgJGOgiagaiaagaoGICogIGIFOGOOOGGOGOGOGOGOGGOGOGFOGOGO😩😩🈷🍺😩😌🈷🍺😊🎉🈷🎉😊❤️‍🔥⚠️😆🔔💀🎉😩🎉⚠️😊🥫🎉💕🚭😆🥤🦵😌🚽🌊😊💀🥫⚠️❤️‍🔥🥫⚠️❤️‍🔥🌊😊💀💕😫🚭🗨️🚽🗨️🏀😊😚😊🏀😌🕐🕐🥫🈷😜🏀🥤🏀🚭😆🥫🥤😌🥤🚭😆🚭🥤😌😜😌🚽🥵🥵🥵🥵🥵🧀 GFENISPOOPNISMPOSTERAMOGUSUSSYERIUSMANMEN

“Ngh…”

A tingle slowly climbs up my limbs, then spreads throughout the rest of my body. It’s probably a hopeful sign that my paralysis is wearing off, but the sensation of it is unbearable. It’s as though millions of tiny insects are crawling inside my body. I’m almost thankful that I still can’t move because otherwise, I would most likely claw my own skin off to try and make it stop.

**Comment by anonymousomeone** [comment]
Ryan Shaw: you remember that time I [EXPLICIT CONTENT REDACTED] Scranton Reality Anchor ( ͡° ͜ʖ ͡°)

Agent █████: I was supposed to take amnestics after that

Ryan Shaw: yeah but you didn't
Ryan Shaw: nnnff yeah you keep lyin to yourself
Ryan Shaw: I'll see you when you get back to the Site

Agent █████: hell yeah you will. gonna put my Keter-class anomaly in your containment chamber

**Comment by Eishaaya** [comment]
Zalander, go away, if you actually have a problem, message me
